### ISSUE TITLE
Pre-generated messages are distinguishable from randomly generated ones due to inconsistent capitalization

### ISSUE THREAD

**Issue by nickelization** [dpark6060/rtstatlib#1]
I like both the one-off messages and the generated ones, but it's too easy to see at a glance whether a message is one-off or generated because capitalization differs between the two message types. For example, a generated message might be `Analyzing Depleted Models`, but a one-off might look like `Deconvolving kernel`.

I think either the one-off messages should be changed so that most words are capitalized there too, or the message generator should be altered so that only the first word is capitalized. Let me know what you think the correct fix is for this, and I'd be happy to file a PR. Thanks in advance!

**Comment by dpark6060** [comment]
A lobotomy will remove this issue from your awareness.  Solved
